apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-name
  region: ap-southeast-1
  version: "1.27"


kubernetesNetworkConfig:
  ipFamily: IPv4 # or IPv6

addons:
  - name: vpc-cni
    version: latest
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest
  - name: aws-ebs-csi-driver
#  - name: aws-load-balancer-controller

iam:
  withOIDC: true

vpc:
  cidr: 192.168.0.0/16
  clusterEndpoints:
    publicAccess: true
    privateAccess: true

managedNodeGroups:
  - name: neo4j-node-group-cluster-name
    instanceType: t4g.large
    iam:
      withAddonPolicies:
        ebs: true
        awsLoadBalancerController: true
    desiredCapacity: 3
    minSize: 1
    maxSize: 4
    volumeSize: 100
    availabilityZones: ["ap-southeast-1a", "ap-southeast-1b", "ap-southeast-1c"]
    ssh:
      publicKey: "changeme"
