apiVersion: v1
kind: Service
metadata:
  annotations:
    helm.sh/resource-policy: keep
    meta.helm.sh/release-name: server-6
    meta.helm.sh/release-namespace: neo4j
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  labels:
    app: multicluster
    app.kubernetes.io/managed-by: Helm
    helm.neo4j.com/neo4j.name: multicluster
    helm.neo4j.com/service: neo4j
  name: multicluster-lb-neo4j-6
  namespace: neo4j
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Local
  internalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 7474
    protocol: TCP
    targetPort: 7474
  - name: https
    port: 7473
    protocol: TCP
    targetPort: 7473
  - name: tcp-bolt
    port: 7687
    protocol: TCP
    targetPort: 7687
  - name: tcp-boltrouting
    port: 7688
    protocol: TCP
    targetPort: 7688
  - name: tcp-discovery
    port: 5000
    protocol: TCP
    targetPort: 5000
  - name: tcp-raft
    port: 7000
    protocol: TCP
    targetPort: 7000
  - name: tcp-tx
    port: 6000
    protocol: TCP
    targetPort: 6000
  publishNotReadyAddresses: true
  selector:
    app: multicluster
    helm.neo4j.com/clustering: "true"
    helm.neo4j.com/neo4j.loadbalancer: include
    helm.neo4j.com/instance: server-6
  sessionAffinity: None
  type: LoadBalancer
