apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-name-2
  region: ap-southeast-1
  version: "1.27"

kubernetesNetworkConfig:
  ipFamily: IPv4 # or IPv6

addons:
  - name: vpc-cni
    version: latest
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest
  - name: aws-ebs-csi-driver
#  - name: aws-load-balancer-controller

vpc:
  id: "vpc-changeme"  # (optional, must match VPC ID used for each subnet below)
  cidr: "192.168.0.0/16"       # (optional, must match CIDR used by the given VPC)
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
  subnets:
    # must provide 'private' and/or 'public' subnets by availability zone as shown
    public:
      ap-southeast-1a:
        id: "subnet-changeme"
        cidr: "192.168.64.0/19" # Example; (optional, must match CIDR used by the given subnet)

      ap-southeast-1b:
        id: "subnet-changeme"
        cidr: "192.168.32.0/19"  # (optional, must match CIDR used by the given subnet)

      ap-southeast-1c:
        id: "subnet-changeme"
        cidr: "192.168.0.0/19"   # (optional, must match CIDR used by the given subnet)

    private:
      ap-southeast-1a:
        id: "subnet-changeme"
        cidr: "192.168.160.0/19" # (optional, must match CIDR used by the given subnet)

      ap-southeast-1b:
        id: "subnet-changeme"
        cidr: "192.168.128.0/19"  # (optional, must match CIDR used by the given subnet)

      ap-southeast-1c:
        id: "subnet-changeme"
        cidr: "192.168.96.0/19"   # (optional, must match CIDR used by the given subnet)

iam:
  withOIDC: true

managedNodeGroups:
  - name: neo4j-node-group-cluster-name-2 
    instanceType: t4g.large
    iam:
      withAddonPolicies:
        ebs: true
        awsLoadBalancerController: true
    desiredCapacity: 3
    minSize: 1
    maxSize: 4
    volumeSize: 100
    availabilityZones: ["ap-southeast-1a", "ap-southeast-1b", "ap-southeast-1c"]
    ssh:
      publicKey: "changeme"
